### ISSUE TITLE
I am only able to see the screen with restart and rules option.

### ISSUE THREAD

**Issue by Chaitanyassr** [bing101/Starving-Snake#1]
I see a window with restart and rules option when i open the html file and after that only rule button works.

- browser - [chrome,edge,firefox,internet explorer]

![Screenshot (209)](https://user-images.githubusercontent.com/30374226/78407206-e66b2000-7621-11ea-8801-f085f433c900.png)

**Comment by arjkashyap** [comment]
There was some error in the path I had given for the load image component. It should work fine now..
